export enum Errors {
  API_ERROR = 'API_ERROR',
  JOI_SCHEMA_NOT_FOUND = 'JOI_SCHEMA_NOT_FOUND',
  VALIDATION_EMAIL_MALFORMED = 'VALIDATION_EMAIL_MALFORMED',
  VALIDATION_PASSWORD_LENGTH = 'VALIDATION_PASSWORD_LENGTH',
  CUSTOMER_EXIST = 'CUSTOMER_EXIST',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  USE_GOOGLE_LOGIN = 'USE_GOOGLE_LOGIN',
  CUSTOMER_NOT_FOUND = 'CUSTOMER_NOT_FOUND',
  REQUEST_NOT_FOUND_OR_EXPIRED = 'REQUEST_NOT_FOUND_OR_EXPIRED',
  INCORRECT_PROVIDER = 'INCORRECT_PROVIDER',
}
