export enum Errors {
  API_ERROR = 'API_ERROR',
  JOI_SCHEMA_NOT_FOUND = 'JOI_SCHEMA_NOT_FOUND',
  VALIDATION_EMAIL_MALFORMED = 'VALIDATION_EMAIL_MALFORMED',
  VALIDATION_PASSWORD_LENGTH = 'VALIDATION_PASSWORD_LENGTH',
  USER_EXIST = 'USER_EXIST',
}
